In [1]:
import numpy as np

In [3]:
21%2 

1

In [5]:
V = np.ones(3)[None, :] * np.arange(3)[:, None]

print(V)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]


In [2]:
22//2

11

In [ ]:
plaquette_coordinates = [[1,1], [2,2], [3,3]]
plaquette = {}

for i,a in enumerate(plaquette_coordinates):
    plaquette[i] = [a[0],a[1]]

print(plaquette)


{0: [1, 1], 1: [2, 2], 2: [3, 3]}
0
1
2


In [4]:
for p in plaquette:
    print(p)

0
1
2


In [9]:
import numpy as np
x_list = [2,3,4,5,5,6,4]

mean_x = np.sum(x_list)/len(x_list)

print(mean_x)


4.142857142857143


In [5]:
import numpy as np
listt = [(1,2), (3,4)]
listt = np.array(listt)
print(listt)
print(listt[1,1])

[[1 2]
 [3 4]]
4


In [6]:
listt = listt.tolist()
print(listt)

[[1, 2], [3, 4]]


In [7]:
for i,j in listt:
    print(i,j)

1 2
3 4


In [1]:
3//2

1

In [22]:
import numpy as np

majoranas = np.zeros(10)
majoranas[[5,2]] = 1  # sets all specified indices to 1
majoranas_bool = majoranas.astype(bool)	
print(majoranas_bool)
num_ones = np.sum(majoranas_bool)
print(num_ones)
prefactor_maj = 1j**(num_ones/2) 

[False False  True False False  True False False False False]
2


In [23]:
matrix = np.zeros((10,10))
for i in range(10):
    for j in range(10):
        matrix[i,j] = i+j/10
print(matrix)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


In [24]:
print(matrix[majoranas_bool][:, majoranas_bool])

[[2.2 2.5]
 [5.2 5.5]]


In [25]:
from pfapack import pfaffian as pf

In [32]:
a = np.array([[0,1., 2.], [-1.,0, 3.], [-2., -3., 0]])
print(a)

[[ 0.  1.  2.]
 [-1.  0.  3.]
 [-2. -3.  0.]]


In [33]:
print(pf.pfaffian(a))

0
