In [1]:
import numpy as np

In [3]:
21%2 

1

In [5]:
V = np.ones(3)[None, :] * np.arange(3)[:, None]

print(V)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]


In [2]:
22//2

11

In [ ]:
plaquette_coordinates = [[1,1], [2,2], [3,3]]
plaquette = {}

for i,a in enumerate(plaquette_coordinates):
    plaquette[i] = [a[0],a[1]]

print(plaquette)


{0: [1, 1], 1: [2, 2], 2: [3, 3]}
0
1
2


In [4]:
for p in plaquette:
    print(p)

0
1
2


In [9]:
import numpy as np
x_list = [2,3,4,5,5,6,4]

mean_x = np.sum(x_list)/len(x_list)

print(mean_x)


4.142857142857143


In [5]:
import numpy as np
listt = [(1,2), (3,4)]
listt = np.array(listt)
print(listt)
print(listt[1,1])

[[1 2]
 [3 4]]
4


In [6]:
listt = listt.tolist()
print(listt)

[[1, 2], [3, 4]]


In [7]:
for i,j in listt:
    print(i,j)

1 2
3 4


In [1]:
3//2

1