In [1]:
import numpy as np

In [3]:
21%2 

1

In [5]:
V = np.ones(3)[None, :] * np.arange(3)[:, None]

print(V)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]


In [2]:
22//2

11

In [ ]:
plaquette_coordinates = [[1,1], [2,2], [3,3]]
plaquette = {}

for i,a in enumerate(plaquette_coordinates):
    plaquette[i] = [a[0],a[1]]

print(plaquette)


{0: [1, 1], 1: [2, 2], 2: [3, 3]}
0
1
2


In [4]:
for p in plaquette:
    print(p)

0
1
2


In [9]:
import numpy as np
x_list = [2,3,4,5,5,6,4]

mean_x = np.sum(x_list)/len(x_list)

print(mean_x)


4.142857142857143


In [5]:
import numpy as np
listt = [(1,2), (3,4)]
listt = np.array(listt)
print(listt)
print(listt[1,1])

[[1 2]
 [3 4]]
4


In [6]:
listt = listt.tolist()
print(listt)

[[1, 2], [3, 4]]


In [7]:
for i,j in listt:
    print(i,j)

1 2
3 4


In [1]:
3//2

1

In [22]:
import numpy as np

majoranas = np.zeros(10)
majoranas[[5,2]] = 1  # sets all specified indices to 1
majoranas_bool = majoranas.astype(bool)	
print(majoranas_bool)
num_ones = np.sum(majoranas_bool)
print(num_ones)
prefactor_maj = 1j**(num_ones/2) 

[False False  True False False  True False False False False]
2


In [23]:
matrix = np.zeros((10,10))
for i in range(10):
    for j in range(10):
        matrix[i,j] = i+j/10
print(matrix)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


In [24]:
print(matrix[majoranas_bool][:, majoranas_bool])

[[2.2 2.5]
 [5.2 5.5]]


In [25]:
from pfapack import pfaffian as pf

In [32]:
a = np.array([[0,1., 2.], [-1.,0, 3.], [-2., -3., 0]])
print(a)

[[ 0.  1.  2.]
 [-1.  0.  3.]
 [-2. -3.  0.]]


In [33]:
print(pf.pfaffian(a))

0


In [35]:
listt = [0,1,2,3,4,5,6,7]

for i in listt[:4:2]:
    print(i)

0
2


In [11]:
listt = [[0,1]]

for a in listt:
    print(a)
    for i,j in a:
        print(i,j)

[0, 1]


TypeError: cannot unpack non-iterable int object

In [13]:
listt = [[[0,1]]]

for a in listt:
    print(a)
    for i,j in a:
        print(i,j)

[[0, 1]]
0 1


In [1]:
import numpy as np

aaa = np.array([12,45,332,2,345,5,6])

aaa = aaa/np.sum(aaa)

In [2]:
print(np.sum(aaa))

1.0


In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print((a/b).tolist())

[1.0, 1.0, 1.0, 1.0, 1.0]


In [9]:
import numpy as np
T_list_1 = np.linspace(1,0.1,25).tolist()
print(T_list_1)

[1.0, 0.9625, 0.925, 0.8875, 0.85, 0.8125, 0.775, 0.7375, 0.7, 0.6625000000000001, 0.625, 0.5875, 0.55, 0.5125, 0.475, 0.4375, 0.4, 0.36250000000000004, 0.32500000000000007, 0.2875, 0.25, 0.21250000000000002, 0.17500000000000004, 0.13750000000000007, 0.1]


In [1]:
import numpy as np
from scipy.linalg import schur, eig

# example skew-symmetric matrix
A = np.array([[ 0.0, -2.0,  0.0],
              [ 2.0,  0.0, -3.0],
              [ 0.0,  3.0,  0.0]])

# real Schur
T_real, Q_real = schur(A, output='real')
# complex Schur
T_comp, Q_comp = schur(A, output='complex')
# direct eigen-decomposition (complex eigenvalues/vectors)
w, v = eig(A)

print("Real Schur T:\n", T_real)
print("Complex Schur T (diagonal = eigenvalues):\n", T_comp)
print("Eigenvalues:\n", w)


Real Schur T:
 [[ 0.          0.          0.        ]
 [ 0.          0.         -3.60555128]
 [ 0.          3.60555128  0.        ]]
Complex Schur T (diagonal = eigenvalues):
 [[ 0.00000000e+00+3.60555128e+00j  1.00533848e-16+4.41297874e-16j
  -6.87546415e-17+1.89812060e-16j]
 [ 0.00000000e+00+0.00000000e+00j  1.95078010e-16-5.22183295e-18j
  -1.92557059e-16-2.48344938e-16j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  -8.29838179e-17-3.60555128e+00j]]
Eigenvalues:
 [0.+0.j         0.+3.60555128j 0.-3.60555128j]
